Admin domain blocks - adding the new v4 admin API endpoints
neet/masto.js pull request #739
Opened 2022-12-02 16:41 UTC by JacksonSamuel42

2022-12-02 17:10 UTC, neet requested changes
- Masto.js internally converts property names from `snake_case` to `camelCase` to comply with JS conventions, so please update all `snake_cases` to annotate types properly
- It seems you forgot to add `export` to sec/entities/admin/index.ts. Otherwise you cannot `import from "masto"` https://github.com/neet/masto.js/blob/main/src/entities/admin/index.ts

2022-12-02 17:10 UTC, neet commented on src/entities/admin/domain-blocks.ts
> +export interface DomainBlocks {
It should be a singular `DomainBlock`

2022-12-02 17:10 UTC, neet commented on src/entities/admin/domain-blocks.ts
> +  created_at: Date | string;
We are not converting ISO timestamps to a Date object so use string instead

2022-12-02 17:10 UTC, neet commented on src/repositories/admin/domain-blocks-repository.ts
> +  readonly reject_media?: boolean | false;
`boolean | false` doesn't make sense because `false` is a subset of `Boolean`. You are seemingly using union types for marking the default values for a parameter, but it's not what union type is for. Consider removing the `| false` as well as other lines using this technique.

2022-12-02 17:10 UTC, neet commented on src/repositories/admin/domain-blocks-repository.ts
> +  @version({ since: '2.9.1' })
All of `/api/v1/admin/domain_blocks` APIs are available since 4.0.0

2022-12-02 17:10 UTC, neet commented on src/repositories/admin/domain-blocks-repository.ts
> +  domain: string;
It should be marked as `readonly` because we don't mutate the argument for sending the request.

2022-12-02 17:10 UTC, neet commented on src/repositories/admin/domain-blocks-repository.ts
> +export interface AdminDomainBlocksFetchParams {
It's not for `fetch` method, so should be named like `AdminBlockDomainParams`

2022-12-02 17:10 UTC, neet commented on src/repositories/admin/domain-blocks-repository.ts
> +  delete(id: string): Promise<void> {
I'd like to name it `remove` for consistency https://github.com/neet/masto.js/search?q=remove

2022-12-02 17:33 UTC, JacksonSamuel42 commented
@neet i will work in this currections

2022-12-02 18:38 UTC, closed without merging

2022-12-03 10:50 UTC, JacksonSamuel42 commented on src/entities/admin/domain-blocks.ts
> +export interface DomainBlocks {
i dont undestand the snack_case point i put all properties in camelCase it should be everything ok

2022-12-03 10:56 UTC, JacksonSamuel42 commented on src/entities/admin/domain-blocks.ts
> +export interface DomainBlocks {
@neet i get the point kk

2022-12-03 10:57 UTC, JacksonSamuel42 commented on src/entities/admin/domain-blocks.ts
> +export interface DomainBlocks {
nevermind