Add FilterResult interface and optional filtered prop to Status
neet/masto.js pull request #740
Opened 2022-12-02 17:13 UTC by ayoayco

This PR will
1. add the optional `filtered` prop to Status https://docs.joinmastodon.org/entities/Status/#filtered
2. add a new interface FilterResult https://docs.joinmastodon.org/entities/FilterResult/

2022-12-02 17:31 UTC, neet commented
@ayoayco CI seems to be failing due to Prettier warning. Can you `yarn run test:eslint --fix`?

2022-12-02 17:32 UTC, ayoayco commented
Sorry missed that. Fixed!

2022-12-02 17:35 UTC, neet requested changes

2022-12-02 17:35 UTC, neet commented on src/entities/filter-result.ts
> +  status_matches: string[] | null;
It should be `statusMatches`

2022-12-02 17:36 UTC, ayoayco commented on src/entities/filter-result.ts
> +  status_matches: string[] | null;
Fixed!

2022-12-02 17:42 UTC, ayoayco commented
If I need to add tests, we can keep this open and I will do it maybe tomorrow. :)

2022-12-03 02:59 UTC, merged

2022-12-03 03:02 UTC, neet commented
I also added `filterAction` in #742