fix: add value type of done result
neet/masto.js pull request #800
Opened 2023-01-09 15:54 UTC by sxzz

As returned here, `value` is always `undefined`.
https://github.com/neet/masto.js/blob/fbfd515ee3ef09e7050868d0d886993f0c93e611/src/paginator.ts#L21

So I add the `undefined` param into `IteratorResult`, otherwise, the default value is any. It'll break strict type.

2023-01-09 15:56 UTC, sxzz commented on src/paginator.ts
> +    return this.next().then((value) => onfulfilled(value.value!), onrejected);
The first item won't be undefined, so I added a non-assertion operator here.

2023-01-09 23:00 UTC, neet requested changes
Thank you for your contribution! I was misunderstanding what `TReturn` is for.

Can you also update [`Paginator#return`](https://github.com/sxzz/masto.js/blob/1820b97111000d5a213ff198b0c7f4daa7979b2d/src/paginator.ts#L42-L47)? Currently, it doesn't meet the updated interface. `lib.es2018` says:

```ts
interface AsyncIterator<T, TReturn = any, TNext = undefined> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): Promise<IteratorResult<T, TReturn>>;
    return?(value?: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<T, TReturn>>;
    throw?(e?: any): Promise<IteratorResult<T, TReturn>>;
}

interface AsyncIterable<T> {
    [Symbol.asyncIterator](): AsyncIterator<T>;
}

interface AsyncIterableIterator<T> extends AsyncIterator<T> {
    [Symbol.asyncIterator](): AsyncIterableIterator<T>;
}
```

Although `AsyncIterrableIterator` (which we're using now) doesn't specify second and third type parameters for some reason, `return` looks natural to only accept `undefined` as its argument. e.g.

```ts
async return(value?: undefined | PromiseLike<undefined>): : Promise<IteratorResult<Entity, undefined>> {
  return {
    done: true,
    value: await value,
  };
}
```

2023-01-09 23:00 UTC, neet commented on src/paginator.ts
> +    return this.next().then((value) => onfulfilled(value.value!), onrejected);
OK! Can you also describe it in a comment along with the `eslint-disable`?

2023-01-10 06:06 UTC, sxzz commented
@neet Updated.

2023-01-10 06:26 UTC, neet approved these changes

2023-01-10 06:27 UTC, merged